give @s elleedog:rbow_helmet
give @s elleedog:rbow_chestplate
give @s elleedog:rbow_leggings
give @s elleedog:rbow_boots
give @s elleedog:rbow_sword
give @s elleedog:rbow_pickaxe
give @s elleedog:rbow_axe
give @s elleedog:rbow_shovel
give @s elleedog:rbow_hoe
give @s elleedog:rbow_spear
give @s minecraft:shield
give @s pet:morpher_book
