// Shared by every <feature>.test.ts. A test bundle holds one feature's scripts plus these tests, because a
// SimulatedPlayer exists only in the script module that spawned it: other packs' modules see it as undefined.
import type { Player } from "@minecraft/server";
import { register, type Test } from "@minecraft/server-gametest";

export const CLASS = "ed67";
/** 7x5x7: stone in its bottom layer, air above. Generated by tools/bds/gametest.ts. */
export const FLOOR = "ed67:floor";
/** The floor with an oak stair one layer up at x 3, z 3, facing north (its open side towards z = 1). */
export const STAIR = "ed67:stair";
/**
 * Test coordinates are relative to the structure block, and the engine places a structure's bottom layer one
 * block above it: relative y = 0 is the structure block, GROUND is the stone floor, STAND is where feet go.
 */
export const GROUND = 1;
export const STAND = 2;

/** Registers one `ed67:<name>` test; tools/bds/gametest.ts reads the names back from this call. */
export function defineTest(name: string, structure: string, maxTicks: number, body: (test: Test) => void): void {
  register(CLASS, name, body).structureName(structure).maxTicks(maxTicks).tag(CLASS);
}

/** Runs one of the add-on's commands as the player; a failure result throws, which the assertions judge. */
export function run(player: Player, command: string): void {
  try {
    player.runCommand(command);
  } catch (error) {
    console.warn(`[gametest] ${command}: ${String(error)}`);
  }
}

export function inventoryHas(player: Player, typeId: string): boolean {
  const container = player.getComponent("minecraft:inventory")?.container;
  if (!container) return false;
  for (let slot = 0; slot < container.size; slot++) if (container.getItem(slot)?.typeId === typeId) return true;
  return false;
}
